anchor_version = "0.24.2"
solana_version = "1.14.28"

[features]
seeds = true

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/virajkokane/.config/solana/id.json"

[programs.mainnet]
merkle_distributor = "E4TrccmubxwNNdHQitRsbbMoumoYd1HPVJ7Rp2R1MMek"

[programs.devnet]
merkle_distributor = "E4TrccmubxwNNdHQitRsbbMoumoYd1HPVJ7Rp2R1MMek"

[programs.testnet]
merkle_distributor = "E4TrccmubxwNNdHQitRsbbMoumoYd1HPVJ7Rp2R1MMek"

[programs.localnet]
merkle_distributor = "E4TrccmubxwNNdHQitRsbbMoumoYd1HPVJ7Rp2R1MMek"

[scripts]
test = "yarn mocha"
